[package]
name = "vsq"
version = "0.1.7"
edition = "2021"

[dependencies]
trust-dns-resolver = "0.23.2"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.41"

[features]
signals = []
